### ISSUE TITLE
Duppi crashes when trying to download language file

### ISSUE THREAD

**Issue by halamix2** [elbereth/DragonUnPACKer#174]
Tested on Windows 10 and wine 2.21:
Log:
`Unhandled: EIdIOHandlerPropInvalid IOHandler value is not valid`
Duppi shows error window and closes itself after clicking OK.

**Comment by elbereth** [comment]
It is not crashing for me...
Windows 10 here.

![capture](https://user-images.githubusercontent.com/1632446/35771627-9f337e26-08f5-11e8-857c-81b2f5071590.PNG)

There was a problem on server side returning UTF-8 charset (due to PHP 7.2 new defaults), added a work around for that. But this was not causing crashes.

**Comment by Halamix2** [comment]
5.7.0.284 beta and 5.7.1.296 nightly-g24e92af-20180 gives me the same error,
I've got `server contacted successfully`, then `disconnecting`, `disconnected` and this error right after. (I've got video of the whole log since error window disallows me to copy the log directly)

Screenshot from WINE:
![error](https://user-images.githubusercontent.com/5176598/35773151-19a1e284-094a-11e8-91c9-1c007f82a85b.png)

**Comment by elbereth** [comment]
Ok, you told me it crashed on start but that can only happen after you press Download with an update selected. Will have a look when possible.

**Comment by elbereth** [comment]
This is fixed I think I had misconfigured the server (plus I lost the database behind the DUS server).
